//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public string Numero_Cuenta { get; set; }
        public string Cedula_Titular { get; set; }
        public string Nombre_Titular { get; set; }
        public string Tipo_cuenta { get; set; }
        public Nullable<int> Saldo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
